# Generated by Django 2.2.16 on 2022-04-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20220425_1830'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favorite',
            name='recipe_user_unique',
        ),
        migrations.RemoveConstraint(
            model_name='shoppingcart',
            name='unique_user_recipe',
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='favorite_unique'),
        ),
        migrations.AddConstraint(
            model_name='shoppingcart',
            constraint=models.UniqueConstraint(fields=('recipe', 'user'), name='shopping_cart_unique'),
        ),
    ]
