# Generated by Django 2.2.16 on 2022-04-26 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220419_0725'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscribe',
            constraint=models.UniqueConstraint(fields=('subscribing', 'user'), name='subscribe_unique'),
        ),
    ]
